initialhsp = random_range(-4, 4)
initialvsp = random_range(-4, 0)
depth = 1
spr_dead = spr_debris_metalrespawn
respawnblock = 100
destroyed = false
visible = true
image_speed = 0.35
x = xstart
y = ystart
