_message_array[0][0] = "It has come to our attention that you PTV viewers out there must still have no clue what this place may be.."
_message_array[1][0] = "Luckily for you, we have found a solution by striking a conversation with 2 of the robot workers stationed in this area of the building."
_message_array[2][0] = "Yes-a. I am one of many lifeless workers in this establishment-a."
_message_array[3][0] = "Us peppinbots are tasked with assuring the utmost quality in our artificial pizzas-a"
_message_array[4][0] = "openwoag:And we the Noibots are here to get the peppinbots to make sure any fatty italian chefs that find their way into this factory will not make it out alive for us!:closedwoag"
